---
title: Вязание и Мода
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: 
email: vyazanieimoda.ru@yandex.ru
description: ''
baseurl: ''
url: ''
twitter_username: 
github_username: 
rss: rss
show_excerpts: false
sass:
  style: :compressed
minima:
  date_format: "%b %-d, %Y"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
theme: minima
exclude:
- Gemfile
- Gemfile.lock
permalink: "/:categories/:title.html"
paginate: 4
paginate_path: "/page:num/"
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
